### ISSUE TITLE
Make it easy for users to invite their friends/colleagues to the website

### ISSUE THREAD

**Issue by JahBrewski** [Sozogo/sozogo#30]
Was watching a TED talk today by Elon Musk (SpaceX, PayPal, Tesla) and he was talking about how fast PayPal spread once they launched. 100k users in the first month! He said you could basically plot the growth the same way you plot bacterial growth of a petri dish... each person invited 2 (or 3) people, who in turn invited 2 or 3 people, who in turn...

I say this because I think we should think about ways to make it easy for users to invite other people to they website. Maybe this is simply through a form that pops up asking them to send email invites to their friends.. Maybe we could hook into Facebook and have them invite their Facebook friends.. Not sure exactly. Wanted to get input on this.

Thoughts @losimpson @tlbrew ?

**Comment by losimpson** [comment]
@JahBrewski 100k in the first month!? Wow! Well wouldn't that be a blessing! If possible, it may be best to hit them with as many modes as possible, ie. Facebook and email. I had mentioned in the integrating Social Media issue the ability to pull information from the user to create a SozoGo volunteer profile. That account link could allow for the ability for users to both share events, and invite new friends to like our Facebook page, which could both help with that. And email sounds simple enough as well with some sort of popup. Little unrelated, but should we put a place on the home page like we had on the splash page to get emails for newsletters, or a check box when signing up that they would like to receive newsletters and we can use the email they give us to sign up?

Additional ways we may be able to add to this is with the addition of gameafication to the website, it can give people the motivation to invite friends and get 100 points, and we can also add a badge for inviting friends, and liking our facebook page. 

Definitely a good idea if we can do it. Can we think of any other clever ways to try to spur other people to advertise? Perhaps making our logos available for download so that other people can spread the logo on things like their church bulletins or something?

**Comment by losimpson** [comment]
Not sure if it'd work but trying to put more clever ideas out there to get people to spread SozoGo, we could make a volunteer event to share on Facebook as a form of volunteering.

**Comment by losimpson** [comment]
combined in: Integrate with Social Media
